---
- name: Deploy GitLab Runner with host network and S3 cache
  hosts: localhost
  become: true
  vars:
    # GitLab Runner configuration
    gitlab_runner_name: "host-network-runner"
    gitlab_runner_url: "https://git.testingmode.com/"
    gitlab_runner_registration_token: "your-registration-token"
    gitlab_runner_registration_method: "legacy"
    
    # Use host network for better connectivity
    docker_use_host_network: true
    
    # S3 cache configuration
    cache_type: "s3"
    cache_s3_server_address: "192.168.5.3:9000"
    cache_s3_access_key: "pw8YigbnEqREGaLGV3A6"
    cache_s3_secret_key: "aVwHCIWyePfLUr5qDLMGajkXmsGgMXTY1nqQGXXX"
    cache_s3_bucket_name: "gitlab-cache"
    cache_s3_insecure: true
    
    # Docker configuration
    docker_image: "alpine:3.21.0"
    docker_privileged: true
    docker_services_privileged: true
    docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/app_data/grunner/cache:/cache"
    
    # Runner configuration
    gitlab_runner_tags: ["host-network", "s3-cache"]
    gitlab_runner_output_limit: 52428800

  roles:
    - atlet99.gitlab-docker-runner 