---
- name: Inspect runner image
  command: docker image inspect {{ runner_image }}
  register: _img_inspect
  failed_when: false
  changed_when: false

- name: Remove broken image
  command: docker rmi -f {{ runner_image }}
  when: >
    _img_inspect.rc != 0 or
    ('Internal Server Error' in (_img_inspect.stderr | default('') | string)) or
    ('no such file or directory' in (_img_inspect.stderr | default('') | string))

- name: Pull runner image
  command: docker pull {{ runner_image }}
  register: _pull_fix
  changed_when: "'Downloaded newer image' in (_pull_fix.stdout | default(''))"

- name: Restart docker daemon (optional)
  service:
    name: docker
    state: restarted
  when: docker_restart_on_overlay_error | default(false) | bool