---
# Main tasks for GitLab Runner
# Uses unified registration logic

- name: Check Docker installation
  command: docker --version
  register: docker_check
  failed_when: docker_check.rc != 0
  changed_when: false

- name: Check Docker network (if needed)
  command: docker network inspect {{ docker_network }}
  register: network_check
  failed_when: network_check.rc not in [0, 1]
  changed_when: false
  when:
    - not runner_network_per_build
    - docker_network is defined
    - docker_network != ""

- name: Create custom network (if needed)
  command: >
    docker network create --driver bridge {% if docker_network_subnet is defined and docker_network_subnet != "" %} --subnet={{ docker_network_subnet }} {% endif %} {% if docker_network_gateway is defined and docker_network_gateway != "" %} --gateway={{ docker_network_gateway }} {% endif %} {% if docker_network_options is defined and docker_network_options|length > 0 %} {% for key, value in docker_network_options.items() %} --opt {{ key }}={{ value }} {% endfor %} {% endif %} {{ docker_network }}
  when:
    - not runner_network_per_build
    - docker_network is defined
    - docker_network != ""
    - network_check.rc == 1

# Include unified registration logic
- name: Include unified GitLab Runner registration
  include_tasks: register.yml
