---
- name: Check Docker installation
  command: docker --version
  register: docker_check
  failed_when: docker_check.rc != 0
  changed_when: false

- name: Create runner data directory
  file:
    path: "{{ runner_directory }}"
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Inspect custom network (if needed)
  command: docker network inspect {{ docker_network }}
  register: network_check
  failed_when: network_check.rc not in [0, 1]
  changed_when: false
  when:
    - not runner_network_per_build
    - docker_network is defined
    - docker_network != ""

- name: Create custom network (if needed)
  command: >
    docker network create --driver bridge {% if docker_network_subnet is defined and docker_network_subnet != "" %} --subnet={{ docker_network_subnet }} {% endif %} {% if docker_network_gateway is defined and docker_network_gateway != "" %} --gateway={{ docker_network_gateway }} {% endif %} {% if docker_network_options is defined and docker_network_options|length > 0 %} {% for key, value in docker_network_options.items() %} --opt {{ key }}={{ value }} {% endfor %} {% endif %} {{ docker_network }}
  when:
    - not runner_network_per_build
    - docker_network is defined
    - docker_network != ""
    - network_check.rc == 1

- name: Validate GitLab URL for legacy registration
  uri:
    url: "{{ gitlab_runner_url }}"
    method: GET
    status_code: [200, 401, 403]
    timeout: 30
  register: gitlab_url_check
  when: gitlab_runner_registration_method == "legacy"
  failed_when: false

- name: Fail if GitLab URL is not accessible
  fail:
    msg: "GitLab URL {{ gitlab_runner_url }} is not accessible. Please check the URL and network connectivity."
  when:
    - gitlab_runner_registration_method == "legacy"
    - gitlab_url_check.failed

- name: Generate config.toml for modern registration method
  ansible.builtin.template:
    src: config.toml.j2
    dest: "{{ runner_directory }}/config.toml"
    mode: '0600'
  when: gitlab_runner_registration_method == "modern"

- name: Generate minimal config.toml for legacy registration method
  ansible.builtin.template:
    src: config.toml.j2
    dest: "{{ runner_directory }}/config.toml"
    mode: '0600'
  when: gitlab_runner_registration_method == "legacy"

- name: Verify config file was created for legacy registration
  stat:
    path: "{{ runner_directory }}/config.toml"
  register: config_file_check
  when: gitlab_runner_registration_method == "legacy"

- name: Display config file status
  debug:
    msg: "Config file exists: {{ config_file_check.stat.exists }}"
  when: 
    - gitlab_runner_registration_method == "legacy"
    - config_file_check is defined

- name: Start GitLab Runner container for modern registration
  docker_container:
    name: "{{ gitlab_runner_container_name }}"
    image: "gitlab/gitlab-runner:{{ gitlab_runner_version }}"
    state: started
    restart_policy: always
    recreate: true
    # Pass a list of dictionaries to `networks`.
    # If `runner_network_per_build` is true, pass an empty list => no networks.
    # Otherwise, pass a list with one dict containing the network name (or "bridge" by default).
    networks: "{{ [] if runner_network_per_build else ([{ 'name': docker_network }] if docker_network and docker_network != '' else [{ 'name': 'bridge' }]) }}"
    volumes:
      - "{{ runner_directory }}:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      TZ: "{{ tz }}"
  when: gitlab_runner_registration_method == "modern"

- name: Start GitLab Runner container for legacy registration (temporary)
  docker_container:
    name: "{{ gitlab_runner_container_name }}"
    image: "gitlab/gitlab-runner:{{ gitlab_runner_version }}"
    state: started
    restart_policy: "no"
    recreate: true
    # Pass a list of dictionaries to `networks`.
    # If `runner_network_per_build` is true, pass an empty list => no networks.
    # Otherwise, pass a list with one dict containing the network name (or "bridge" by default).
    networks: "{{ [] if runner_network_per_build else ([{ 'name': docker_network }] if docker_network and docker_network != '' else [{ 'name': 'bridge' }]) }}"
    volumes:
      - "{{ runner_directory }}:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      TZ: "{{ tz }}"
  when: gitlab_runner_registration_method == "legacy"

- name: Wait for GitLab Runner container to be ready
  wait_for:
    timeout: 30
  when: gitlab_runner_registration_method == "legacy"

- name: Construct legacy registration command
  ansible.builtin.set_fact:
    legacy_register_cmd: >
      register
      --non-interactive
      --url "{{ gitlab_runner_url }}"
      --registration-token "{{ gitlab_runner_registration_token }}"
      --name "{{ gitlab_runner_name }}"
      {% if gitlab_runner_tags %}--tag-list "{{ gitlab_runner_tags | join(',') }}"{% endif %}
      --executor docker
      --docker-image "{{ docker_image }}"
      {% if docker_privileged %}--docker-privileged {% endif %}

      {% if docker_volumes %}{% for volume in docker_volumes %}--docker-volumes "{{ volume }}" {% endfor %}{% endif %}
      --docker-extra-hosts "{{ ansible_default_ipv4.address | default(fallback_ip_address) }}:{{ ansible_default_ipv4.address | default(fallback_ip_address) }}"
      {% if docker_shm_size %}--docker-shm-size "{{ docker_shm_size }}"{% endif %}
      {% if docker_pull_policy %}--docker-pull-policy "{{ docker_pull_policy }}"{% endif %}
      {% if docker_helper_image %}--docker-helper-image "{{ docker_helper_image }}"{% endif %}
      {% if docker_isolation %}--docker-isolation "{{ docker_isolation }}"{% endif %}
      {% if docker_services_privileged %}--docker-services-privileged "{{ docker_services_privileged | lower }}"{% endif %}
      {% if docker_allowed_privileged_images %}{% for image in docker_allowed_privileged_images %}--docker-allowed-privileged-images "{{ image }}" {% endfor %}{% endif %}
      {% if docker_allowed_privileged_services %}{% for service in docker_allowed_privileged_services %}--docker-allowed-privileged-services "{{ service }}" {% endfor %}{% endif %}
      {% if docker_cpuset_cpus %}--docker-cpuset-cpus "{{ docker_cpuset_cpus }}"{% endif %}
      {% if docker_cpuset_mems %}--docker-cpuset-mems "{{ docker_cpuset_mems }}"{% endif %}
      {% if docker_cpus %}--docker-cpus "{{ docker_cpus }}"{% endif %}
      {% if docker_cap_add %}{% for cap in docker_cap_add %}--docker-cap-add "{{ cap }}" {% endfor %}{% endif %}
      {% if docker_cap_drop %}{% for cap in docker_cap_drop %}--docker-cap-drop "{{ cap }}" {% endfor %}{% endif %}
      {% if docker_devices %}{% for device in docker_devices %}--docker-devices "{{ device }}" {% endfor %}{% endif %}
      {% if docker_userns_mode %}--docker-userns-mode "{{ docker_userns_mode }}"{% endif %}
      {% if docker_disable_cache %}--docker-disable-cache{% endif %}
      {% if docker_wait_for_services_timeout %}--docker-wait-for-services-timeout "{{ docker_wait_for_services_timeout }}"{% endif %}
      {% if docker_extra_hosts %}{% for host in docker_extra_hosts %}--docker-extra-hosts "{{ host }}" {% endfor %}{% endif %}
      {% if docker_dns %}{% for dns in docker_dns %}--docker-dns "{{ dns }}" {% endfor %}{% endif %}
      {% if docker_dns_search %}{% for dns_search in docker_dns_search %}--docker-dns-search "{{ dns_search }}" {% endfor %}{% endif %}
      {% if docker_security_opt %}{% for opt in docker_security_opt %}--docker-security-opt "{{ opt }}" {% endfor %}{% endif %}
      {% if docker_runtime %}--docker-runtime "{{ docker_runtime }}"{% endif %}
      {% if docker_hostname %}--docker-hostname "{{ docker_hostname }}"{% endif %}
      {% if docker_user %}--docker-user "{{ docker_user }}"{% endif %}
      {% if gitlab_runner_output_limit and gitlab_runner_output_limit > 0 %}--output-limit "{{ gitlab_runner_output_limit }}"{% endif %}
      {% if gitlab_runner_concurrent %}--limit "{{ gitlab_runner_concurrent }}"{% endif %}
      {% if gitlab_runner_environment_flags %}{% for env_flag in gitlab_runner_environment_flags %}--env "{{ env_flag }}" {% endfor %}{% endif %}
      {% if cache_type %}--cache-type "{{ cache_type }}"{% endif %}
      {% if cache_shared %}--cache-shared{% endif %}
      {% if cache_path %}--cache-path "{{ cache_path }}"{% endif %}
      {% if cache_s3_server_address %}--cache-s3-server-address "{{ cache_s3_server_address }}"{% endif %}
      {% if cache_s3_access_key %}--cache-s3-access-key "{{ cache_s3_access_key }}"{% endif %}
      {% if cache_s3_bucket_name %}--cache-s3-bucket-name "{{ cache_s3_bucket_name }}"{% endif %}
      {% if cache_s3_bucket_location %}--cache-s3-bucket-location "{{ cache_s3_bucket_location }}"{% endif %}
      {% if cache_s3_insecure %}--cache-s3-insecure{% endif %}
      {% if cache_s3_authentication_type %}--cache-s3-authentication-type "{{ cache_s3_authentication_type }}"{% endif %}
      {% if cache_s3_server_side_encryption %}--cache-s3-server-side-encryption "{{ cache_s3_server_side_encryption }}"{% endif %}
      {% if cache_s3_server_side_encryption_key_id %}--cache-s3-server-side-encryption-key-id "{{ cache_s3_server_side_encryption_key_id }}"{% endif %}
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""

- name: Display registration command (without secrets)
  debug:
    msg: "Registration command: gitlab-runner {{ legacy_register_cmd }}"
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_register_cmd is defined

- name: Register runner using legacy method
  command: >
    docker exec {{ gitlab_runner_container_name }} gitlab-runner {{ legacy_register_cmd }}
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_register_cmd is defined
  register: legacy_registration_result
  failed_when: legacy_registration_result.rc != 0

- name: Check if runner is already registered
  shell: docker exec {{ gitlab_runner_container_name }} gitlab-runner list 2>/dev/null | grep -q "{{ gitlab_runner_name }}" || echo "not_found"
  register: runner_exists_check
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_register_cmd is defined
  failed_when: false

- name: Display runner existence status
  debug:
    msg: "Runner '{{ gitlab_runner_name }}' exists: {{ runner_exists_check.stdout != 'not_found' }}"
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - runner_exists_check is defined

- name: Wait for registration to complete
  wait_for:
    timeout: 30
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined

- name: Check registration logs for errors
  shell: docker logs {{ gitlab_runner_container_name }} 2>&1 | tail -20
  register: registration_logs
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined

- name: Display registration logs
  debug:
    var: registration_logs.stdout_lines
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - registration_logs is defined

- name: Check registration command output
  debug:
    var: legacy_registration_result.stdout_lines
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined

- name: Check registration command stderr
  debug:
    var: legacy_registration_result.stderr_lines
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined

- name: Stop temporary registration container
  docker_container:
    name: "{{ gitlab_runner_container_name }}"
    state: stopped
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined

- name: Remove temporary registration container
  docker_container:
    name: "{{ gitlab_runner_container_name }}"
    state: absent
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined

- name: Start GitLab Runner container in normal mode (after registration)
  docker_container:
    name: "{{ gitlab_runner_container_name }}"
    image: "gitlab/gitlab-runner:{{ gitlab_runner_version }}"
    state: started
    restart_policy: always
    recreate: true
    networks: "{{ [] if runner_network_per_build else ([{ 'name': docker_network }] if docker_network and docker_network != '' else [{ 'name': 'bridge' }]) }}"
    volumes:
      - "{{ runner_directory }}:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      TZ: "{{ tz }}"
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined

- name: Wait for GitLab Runner to be ready after registration
  wait_for:
    timeout: 60
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined

- name: Wait for new container to be ready
  wait_for:
    timeout: 30
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined

- name: Verify configuration was updated with authentication token
  shell: docker exec {{ gitlab_runner_container_name }} grep -q "^  token = " /etc/gitlab-runner/config.toml
  register: token_verification
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined
  failed_when: token_verification.rc != 0

- name: Display successful registration message
  debug:
    msg: "GitLab Runner successfully registered and authentication token was generated"
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined
    - token_verification is defined
    - token_verification.rc == 0

- name: Display registration failure message
  debug:
    msg: |
      GitLab Runner registration appears to have failed.
      Please check:
      1. Registration token validity and expiration
      2. GitLab URL accessibility
      3. Network connectivity
      4. SSL/TLS certificates
      5. GitLab instance status
      
      You can run the diagnostic script: ./scripts/diagnose-legacy-registration.sh
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined
    - token_verification is defined
    - token_verification.rc != 0

- name: Display registration not attempted message
  debug:
    msg: |
      GitLab Runner registration was not attempted.
      This could be due to:
      1. Missing registration token
      2. Registration token is empty
      3. Registration method is not set to 'legacy'
      
      Please check your variables and try again.
  when: 
    - gitlab_runner_registration_method == "legacy"
    - (gitlab_runner_registration_token is not defined or gitlab_runner_registration_token == "")

- name: Verify GitLab Runner configuration
  shell: docker exec {{ gitlab_runner_container_name }} gitlab-runner verify
  register: runner_verify
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined
  failed_when: false

- name: Display runner verification results
  debug:
    var: runner_verify.stdout_lines
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined
    - runner_verify is defined

- name: Check if authentication token was generated after legacy registration
  shell: docker exec {{ gitlab_runner_container_name }} cat /etc/gitlab-runner/config.toml | grep -E "^  token = " || echo "Token not found"
  register: token_check
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined
  failed_when: false

- name: Display full configuration file content
  shell: docker exec {{ gitlab_runner_container_name }} cat /etc/gitlab-runner/config.toml
  register: config_content
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined
  failed_when: false

- name: Show configuration file content
  debug:
    var: config_content.stdout_lines
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined
    - config_content is defined

- name: Display authentication token status
  debug:
    msg: "Authentication token status: {{ token_check.stdout }}"
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined
    - token_check is defined

- name: Show runner status after legacy registration
  shell: docker exec {{ gitlab_runner_container_name }} gitlab-runner list
  register: runner_status
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined
  failed_when: false

- name: Display runner status
  debug:
    var: runner_status.stdout_lines
  when: 
    - gitlab_runner_registration_method == "legacy"
    - gitlab_runner_registration_token is defined
    - gitlab_runner_registration_token != ""
    - legacy_registration_result is defined
    - runner_status is defined
