---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Check if GitLab Runner container is running
      docker_container_info:
        name: gitlab-runner
      register: runner_container

    - name: Assert GitLab Runner container is running
      assert:
        that:
          - runner_container.exists
          - runner_container.container.State.Running

    - name: Check if config.toml exists
      stat:
        path: /var/lib/gitlab-runner/config.toml
      register: config_file

    - name: Assert config.toml exists
      assert:
        that:
          - config_file.stat.exists
          - config_file.stat.isreg

    - name: Check config.toml permissions
      stat:
        path: /var/lib/gitlab-runner/config.toml
      register: config_perms

    - name: Assert config.toml has correct permissions
      assert:
        that:
          - config_perms.stat.mode == "0600" 